source 'git@git.coding.net:FKLam/XMGFMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'XMGDwonLoadListern_Example' do
  pod 'XMGDwonLoadListern', :path => '../'

  target 'XMGDwonLoadListern_Tests' do
    inherit! :search_paths


  end
end
